---
  - name: Install PostgreSQL package
    apt:
      name: "{{ postgre_install_packages }}"
      autoclean: yes
      state: present
      force_apt_get: yes
#    when: (ansible_distribution_release == distribution_release)

  - name: Create testdb
    become: yes
    become_user: postgres
    postgresql_db:
      name: testdb
      encoding: UTF-8
      template: template0
      state: present

  - name: Create postgre user
    become: yes
    become_user: postgres
    postgresql_user:
      name: "pguser"
      password: "pgpassword"
      db: testdb
      priv: ALL
      state: present
    